---
- hosts: piHole,apps
  become: true
  tasks:
    - name: Updating all packages
      become: true
      become_user: pgerringer
      ansible_become_user: pgerringer
      apt:
         update_cache: yes
         upgrade: dist
         force_apt_get: yes
         cache_valid_time: 3600
         autoremove: yes
         autoclean: yes
