---
- hosts: piHole
  tasks:
    - name: Updating FTL
      shell: pihole updatePihole
      args:
        warn: false

    - name: Updating Gravity
      shell: pihole updateGravity
      args:
        warn: false

- hosts: infra_apps,apps,web,piHole,miners
  tasks:
    - name: Updating all packages
      apt:
         update_cache: yes
         upgrade: dist
         force_apt_get: yes
         cache_valid_time: 3600
         autoremove: yes
         autoclean: yes

    - name: Checking to see if a reboot is needed
      register: reboot_required
      stat:
        path: /var/run/reboot-required

    - name: Rebooting the host if necessary
      reboot:
        msg: "Reboot initiated by Ansible due to system updates"
        connect_timeout: 5
        reboot_timeout: 300
        pre_reboot_delay: 0
        post_reboot_delay: 30
        test_command: uptime
      when: reboot_required.stat.exists == true
