---
- hosts: piHole,apps
  become: yes
  tasks:
    - name: Updating all packages
      ansible_become_user: ansible
      apt:
         update_cache: yes
         upgrade: dist
         force_apt_get: yes
         cache_valid_time: 3600
         autoremove: yes
         autoclean: yes
