---
- hosts: piHole
  tasks:
    - name: Updating FTL
      shell: pihole -up
      args:
        warn: false

    - name: Updating Gravity
      shell: pihole -p
      args:
        warn: false
        
- hosts: piHole,apps,vms
  tasks:
    - name: Updating all packages
      apt:
         update_cache: yes
         upgrade: yes
         force_apt_get: yes
         cache_valid_time: 3600
         autoremove: yes
         autoclean: yes
