---
- hosts: UpdateAndReboot
  hosts: all
  tasks:
    - name: Updating all packages
      become: true
      become_method: sudo
      become_user: root
      remote_user: root
      apt:
        update_cache: yes
        upgrade: yes
        force_apt_get: yes
        cache_valid_time: 3600
        autoremove: yes
        autoclean: yes
